project:
  type: website
  output-dir: docs
  # type: book
website:   
  sidebar:
    style: "docked" # floating
    search: true
    title: "基于Python的经济数据分析与应用"
    contents:
      - text: "前言"
        href: index.qmd
      - section: "Python基础"
        contents:
          - text: "介绍"
            href: intro.qmd          
          - text: "Python语言"
            href: python_basics.qmd
          - text: "Numpy 基础"
            href: numpy.qmd
      - section: "数据分析"
        contents:
          - text: "数据可视化"
            href: matplotlib.qmd
          - text: "Pandas及应用"
            href: pandas.qmd    
          - text: "描述性分析"
            href: text_analysis.qmd
      - section: "回归分析"
        contents:
          - text: "线性回归"
            href: regression.qmd                      
          - text: "逻辑回归"
            href: logistic.qmd
          - text: "Lasso回归"
            href: lasso.qmd
      - text: "总结"
        href: summary.qmd
      - text: "参考文献"
        href: references.qmd
        

       
bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "Table of Contents"
    toc-position: right
  pdf:
    documentclass: ctexbook
    toc: true
    toc-depth: 2
    toc-title: "Table of Contents"
    number-sections: true    
    fig-cap-location: bottom
    fig_caption: true  
    latex-engine: xelatex
    includes:
      in-header: header.tex    
    keep-tex: false
    latex-auto-install: false
    cite-method: biblatex