project:
  type: website
  output-dir: docs  
website:   
  sidebar:
    style: "docked" 
    search: true
    tools: 
      - icon: github
        href: https://github.com/YuMingchaonjnu/Economic-Analysis       
    title: "基于Python的经济数据分析与应用"
    contents:
      - text: "前言"
        href: index.qmd
      - section: "Python基础"
        contents:
          - text: "引言"
            href: intro.qmd          
          - text: "Python基础"
            href: python_basics.qmd
          - text: "Numpy 基础"
            href: numpy.qmd
      - section: "数据分析"
        contents:
          - text: "数据的可视化"
            href: matplotlib.qmd
          - text: "Pandas及应用"
            href: pandas.qmd    
          - text: "数据的统计描述"
            href: eda.qmd
      - section: "回归分析"
        contents:
          - text: "线性回归"
            href: regression.qmd                      
          - text: "逻辑回归"
            href: logistic.qmd
          - text: "Lasso回归"
            href: lasso.qmd
      - text: "总结"
        href: summary.qmd
      - text: "参考文献"
        href: references.qmd
        
  back-to-top-navigation: true
  page-footer:
    left: "Copyright © 2025 YuMingchao"     
    right: "Powered by Quarto"
       
bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "Table of Contents"
    toc-position: right    
    number-sections: false
  
  pdf:
    documentclass: ctexbook
    toc: true
    toc-depth: 2
    toc-title: "Table of Contents"
    number-sections: true    
    fig-cap-location: bottom
    fig_caption: true  
    latex-engine: xelatex
    includes:
      in-header: header.tex    
    keep-tex: false
    latex-auto-install: false
    cite-method: biblatex