project:
  type: website
  output-dir: docs
  # type: book
website:   
  sidebar:
    style: "docked"
    search: true
    title: "基于Python的经济数据分析与应用"
    contents:
      - text: "前言"
        href: index.qmd
      - section: "Python基础"
        contents:
          - text: "介绍"
            href: intro.qmd
          - text: "Python基础"
            href: python_basics.qmd
      - section: "数据分析"
        contents:
          - text: "NumPy与Pandas"
            href: numpy_and_pandas.qmd    
          - text: "探索性数据分析"
            href: text_analysis.qmd
      - text: "总结"
        href: summary.qmd
      - text: "参考文献"
        href: references.qmd
        

       

# book:
#   title: "基于Python的经济数据分析与应用"
#   author: "于明超"
#   date: today
#   chapters:
#     - index.qmd    
#     - intro.qmd
#     - python_basics.qmd
#     - numpy_and_pandas.qmd
#     #- eda.qmd(mac)
#     #- statistics.qmd macbook(mac)
#     #- regression.qmd
#     #- monte_carlo.qmd
#     #- entropy.qmd
#     #- pca.qmd
#     #- io.qmd
#     #- text_analysis.qmd
#     #- trade_flow.qmd
#     - summary.qmd
#     - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "Table of Contents"
    toc-position: right
  pdf:
    documentclass: ctexbook
    toc: true
    toc-depth: 2
    toc-title: "Table of Contents"
    number-sections: true    
    fig-cap-location: bottom
    fig_caption: true  
    latex-engine: xelatex
    includes:
      in-header: header.tex    
    keep-tex: false
    latex-auto-install: false
    cite-method: biblatex